version: 2
jobs:
  build:
    docker:
      - image: hseeberger/scala-sbt
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: run test
          command: |
            sbt test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
